def verify_url(url):

    white_list = ['aajtak.in', 'abcnews.go.com', 'abplive.com', 'afternoonvoice.com', 'aljazeera.com', 'amarujala.com', 'aninews.in', 'apnews.com' 'asianage.com', 'asianetnews.com', 'bbc.co.uk', 'bbc.com', 'bloomberg.com', 'business-standard.com', 'businessinsider.com', 'businesstoday.in', 'businessworld.in', 'caravanmagazine.in', 'cbsnews.com', 'cnbc.com', 'cnn.com', 'cnnnews18.com', 'dailyexcelsior.com', 'dailymail.co.uk', 'dailyo.in', 'dailypioneer.com', 'dainiksaveratimes.com', 'deccanchronicle.com', 'deccanherald.com', 'divyabhaskar.co.in', 'dnaIndia.com', 'dnaindia.com', 'dw.com', 'easternmirrornagaland.com', 'economictimes.indiatimes.com', 'edexlive.com', 'euronews.com', 'financial express.com', 'financialexpress.com', 'firstpost.com', 'forbes.com', 'foxnews.com', 'freepressjournal.in', 'frontline.thehindu.com', 'ft.com', 'goanewshub.com', 'gujaratsamachar.com', 'hindi.news18.com', 'hindustantimes.com', 'huffingtonpost.com', 'huffpost.com', 'ibtimes.co.in', 'independent.co.uk', 'india.com', 'indiainfoline.com', 'indianews.com', 'indianexpress.com', 'indiatimes.com', 'indiatoday.in', 'indiatvnews.com', 'jagran.com', 'kashmirlife.net', 'latimes.com', 'livemint.com', 'lokmat.com', 'mid-day.com', 'millenniumpost.in', 'mirror.co.uk', 'moneybhaskar.com', 'moneycontrol.com', 'morungexpress.com', 'msn.com', 'nagalandpost.com', 'nationalgeographic.com', 'navbharattimes.indiatimes.com', 'nbcnews.com', 'ndtv.com', 'newindianexpress.com', 'news.yahoo.com', 'news18.com', 'news24online.com', 'newsbytesapp.com', 'newsclick.in', 'newslaundry.com', 'newslive.com', 'newsnation.in', 'newstracklive.com', 'newsx.com', 'npr.org', 'nytimes.com', 'oneindia.com', 'opindia.com', 'outlookindia.com', 'politico.com', 'punjabitribuneonline.com', 'punjabkesari.com', 'punjabnewsexpress.com', 'punjabtribune.com', 'rajasthanpatrika.patrika.com', 'rediff.com', 'republicworld.com', 'www.reuters.com', 'sabrangindia.in', 'sakaltimes.com', 'sakshi.com', 'sandesh.com', 'scroll.in', 'siasat.com', 'skynews.com', 'starofmysore.com', 'statetimes.in', 'telanganatoday.com', 'telegraph.co.uk', 'theassamtribune.com', 'theatlantic.com', 'thebetterindia.com', 'thebridgechronicle.com', 'thefinancialexpress.com', 'theguardian.com', 'thehansindia.com', 'thehindu.com', 'thehindubusinessline.com', 'thehitavada.com', 'thelallantop.com', 'theleaflet.in', 'thenewsminute.com', 'thenewsonline.in', 'thenortheasttoday.com', 'theprint.in', 'thequint.com', 'theshillongtimes.com', 'thetimes.co.in', 'thetimes.co.uk', 'thewire.in', 'time.com', 'timesnownews.com', 'timesofindia.indiatimes.com', 'tribuneindia.com', 'tv9bangla.com', 'tv9gujarati.com', 'tv9hindi.com', 'tv9kannada.com', 'tv9malayalam.com', 'tv9marathi.com', 'tv9tamil.com', 'tv9telugu.com', 'usatoday.com', 'vox.com', 'washingtonpost.com', 'wsj.com', 'yahoo.com', 'zeeNews.com', 'zeebiz.com', 'zeenews.india.com']
    black_list = ['Adequacy.org', 'Al-Hudood', 'Awaze Tribune', 'TheBabylonBee.com', 'Bbspot.com', 'TheBeaverton.com', 'TheBetootaAdvocate.com.au', 'BorowitzReport.newyorker.com', 'TheBurrardStreetJournal.com', 'TheChaser.com.au', 'ElChiguireBipolar.net', 'TheCivilian.com.au', 'ClickHole.com', 'Cracked.com', 'Christwire.com', 'TheDailyBonnet.com', 'DailyMash.co.uk', 'DailySquib.co.uk', 'DailyWTF.com', 'TheDailyER.com', 'despeld.nl', 'Exile.ru', 'Der-postillon.com', 'DuffelBlog.com', 'ElKosharyToday.com', 'Fognews.ru', 'FramleyExaminer.co.uk', 'FreeWoodPost.com', 'Hard-Drive.net', 'TheHardTimes.net', 'HumorTimes.com', 'Huzlers.com', 'IslamicaNews.com', 'JournalMourreal.com', 'KhabaristanTimes.com', 'Kyoko-shimbun.jp', 'LandoverBaptist.org', 'LeGorafi.fr', 'GroenkopingsVeckoblad.se', 'LarkNews.com', 'TheLemonPress.co.uk', 'Lercio.it', 'ElMundoToday.com', 'NationalReport.net', 'NewsBiscuit.co.uk', 'NewsThump.com', 'Njuz.net', 'nordpresse.be', 'TheOnion.com', 'TheOxymoron.com', 'ThePoke.co.uk', 'Panorama.co', 'PrivateEye.co.uk', 'IlQuotidianoPazzo.it', 'Reductress.com', 'TheRochdaleHerald.co.uk', 'SatireWire.com', 'ScrappleFace.com', 'Sensacionalista.uol.com.br', 'TheFauxy.com', 'Topeka-News.com', 'TrueNorthTimes.ca', 'TheUnRealTimes.com', 'TimesNewRoman.ro', 'WalkingEagleNews.ca', 'WaterfordWhispersNews.com', 'WeeklyWorldNews.com', 'WorldNewsDailyReport.com', 'Zaytung.com']

    if url in white_list: 
        return True
    
    elif url in black_list:
        return False

    else:
        return None
 

